image: fedora:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


cache:
  paths:
    - .cache/pip

before_script:
  - dnf install libbsd libbsd-devel python clang python-pip -y
  - pip install norminette
  - python -V
  - uname -a

build:
  script:
     - make
     - make clean
     - make fclean
     - make re

test:
  script:
     - make tests

norme:
  script:
     - norminette srcs
     - norminette includes
